# Generated by Django 5.2.4 on 2025-09-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='librarian',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name'], 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
